# Generated by Django 5.2.6 on 2025-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('olid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OLID (OpenLibrary)')),
            ],
        ),
    ]
