# Generated by Django 5.2.6 on 2025-09-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autor_imagem_alter_autor_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='olid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
