# Generated by Django 5.2.6 on 2025-09-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_autor_olid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='imagem',
        ),
        migrations.AddField(
            model_name='autor',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='olid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OLID (OpenLibrary)'),
        ),
    ]
