# Generated by Django 5.2.6 on 2025-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_autor_categoria_livro_delete_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_livro/'),
        ),
    ]
